### ISSUE TITLE
Uncaught exception 'Exception' with message 'Can't find youtube-dl at /usr/local/bin/youtube-dl' 

### ISSUE THREAD

**Issue by jjarroyo** [Rudloff/alltube-example-project#2]
porque sale ese error?

**Comment by Rudloff** [comment]
Hello,

Did you install [youtube-dl](http://rg3.github.io/youtube-dl/)?
You then need to edit [this line](https://github.com/Rudloff/alltube-example-project/blob/master/index.php#L11) so that the path points to where youtube-dl is installed.

**Comment by jjarroyo** [comment]
si muchas gracias
